Redirect to /Guide/
w3c/w3c.github.io pull request #128
Opened 2024-11-07 16:11 UTC by deniak

The following directories have been moved to [the Guide repo](https://github.com/w3c/Guide/):
* documentreview
* manual-of-style
* standards-track
* transitions

2024-11-09 18:03 UTC, vivienlacourba requested changes

2024-11-09 18:03 UTC, vivienlacourba commented on standards-track/index.html
> +<a href="https://www.w3.org/Guide/documentreview/">https://www.w3.org/Guide/documentreview/</a>
```suggestion
  <meta http-equiv="refresh" content="0; url=https://www.w3.org/Guide/standards-track/">
<title>Moved…</title>
</head>
<body onload=' location.href = "https://www.w3.org/Guide/standards-track/" + location.hash; '>
<p>Moved to
<a href="https://www.w3.org/Guide/standards-track/">https://www.w3.org/Guide/standards-track/</a>
```

2024-11-12 09:36 UTC, vivienlacourba approved these changes

2024-11-15 10:46 UTC, plehegar approved these changes

2024-11-15 10:46 UTC, merged